import Mathlib

/-!
# The abstract Manin quotient and maps induced on it

This file formalizes the Manin presentation in the manuscript's subsection
"Modular symbols with coefficients in R". It
does not formalize homogeneous polynomials or the Heilbronn--Merel formula:
those computations are deliberately outside the present implication layer.
Instead, `V` is an arbitrary coefficient module and `S` and `U` are the two
right-action endomorphisms occurring in the Manin presentation.
-/

namespace HeckeCongruences

section ManinPresentation

variable {R V : Type*} [CommRing R] [AddCommGroup V] [Module R V]

/-- The relation module
`V(1+S) + V(1+U+U^2)` in the Manin presentation.  With the row-vector
convention of the manuscript, the images of these endomorphisms are exactly
the submodules generated by the two families of Manin relations. -/
def maninRelations (S U : Module.End R V) : Submodule R V :=
  LinearMap.range (LinearMap.id + S) ⊔
    LinearMap.range (LinearMap.id + U + U ^ 2)

/-- The abstract Manin presentation
`V / (V(1+S) + V(1+U+U^2))`. -/
abbrev ManinQuotient (S U : Module.End R V) :=
  V ⧸ maninRelations S U

/-- An endomorphism of the coefficient module descends to the Manin quotient
as soon as it preserves the Manin relation submodule. -/
def maninQuotientEndomorphism (S U T : Module.End R V)
    (hT : maninRelations S U ≤ Submodule.comap T (maninRelations S U)) :
    Module.End R (ManinQuotient S U) :=
  Submodule.mapQ (maninRelations S U) (maninRelations S U) T hT

theorem maninQuotientEndomorphism_mk (S U T : Module.End R V)
    (hT : maninRelations S U ≤ Submodule.comap T (maninRelations S U))
    (x : V) :
    maninQuotientEndomorphism S U T hT (Submodule.Quotient.mk x) =
      Submodule.Quotient.mk (T x) := by
  exact Submodule.mapQ_apply _ _ _ x

end ManinPresentation

section Transfer

variable {R V₁ V₂ V₃ : Type*} [CommRing R]
  [AddCommGroup V₁] [AddCommGroup V₂] [AddCommGroup V₃]
  [Module R V₁] [Module R V₂] [Module R V₃]

variable (S₁ U₁ : Module.End R V₁) (S₂ U₂ : Module.End R V₂)
  (S₃ U₃ : Module.End R V₃)

/-- The transfer induced on Manin quotients by two coefficient maps which
separately carry Manin relations to Manin relations.  In the manuscript the
two maps are multiplication by `A_m` and by `B_m`. -/
def maninTransfer (A : V₁ →ₗ[R] V₃) (B : V₂ →ₗ[R] V₃)
    (hA : maninRelations S₁ U₁ ≤ Submodule.comap A (maninRelations S₃ U₃))
    (hB : maninRelations S₂ U₂ ≤ Submodule.comap B (maninRelations S₃ U₃)) :
    ManinQuotient S₁ U₁ × ManinQuotient S₂ U₂ →ₗ[R]
      ManinQuotient S₃ U₃ :=
  (Submodule.mapQ (maninRelations S₁ U₁) (maninRelations S₃ U₃) A hA).coprod
    (Submodule.mapQ (maninRelations S₂ U₂) (maninRelations S₃ U₃) B hB)

theorem maninTransfer_mk (A : V₁ →ₗ[R] V₃) (B : V₂ →ₗ[R] V₃)
    (hA : maninRelations S₁ U₁ ≤ Submodule.comap A (maninRelations S₃ U₃))
    (hB : maninRelations S₂ U₂ ≤ Submodule.comap B (maninRelations S₃ U₃))
    (x : V₁) (y : V₂) :
    maninTransfer S₁ U₁ S₂ U₂ S₃ U₃ A B hA hB
        (Submodule.Quotient.mk x, Submodule.Quotient.mk y) =
      Submodule.Quotient.mk (A x + B y) := by
  simp [maninTransfer, Submodule.mapQ_apply]

/-- Surjectivity of coefficient multiplication implies surjectivity of the
induced transfer on Manin quotients. -/
theorem maninTransfer_surjective (A : V₁ →ₗ[R] V₃) (B : V₂ →ₗ[R] V₃)
    (hA : maninRelations S₁ U₁ ≤ Submodule.comap A (maninRelations S₃ U₃))
    (hB : maninRelations S₂ U₂ ≤ Submodule.comap B (maninRelations S₃ U₃))
    (hsurj : Function.Surjective (A.coprod B)) :
    Function.Surjective
      (maninTransfer S₁ U₁ S₂ U₂ S₃ U₃ A B hA hB) := by
  intro z
  obtain ⟨z, rfl⟩ := Submodule.mkQ_surjective (maninRelations S₃ U₃) z
  obtain ⟨⟨x, y⟩, hxy⟩ := hsurj z
  refine ⟨(Submodule.Quotient.mk x, Submodule.Quotient.mk y), ?_⟩
  rw [maninTransfer_mk]
  exact congrArg Submodule.Quotient.mk hxy

end Transfer

section SignedPart

variable {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]

/-- The `ι = ε` submodule.  In applications `ε` is `+1` or `-1`. -/
def signedPart (ι : Module.End R M) (ε : R) : Submodule R M :=
  Module.End.eigenspace ι ε

theorem mem_signedPart_iff {ι : Module.End R M} {ε : R} {x : M} :
    x ∈ signedPart ι ε ↔ ι x = ε • x := by
  exact Module.End.mem_eigenspace_iff

variable {M₁ M₂ M₃ : Type*}
  [AddCommGroup M₁] [AddCommGroup M₂] [AddCommGroup M₃]
  [Module R M₁] [Module R M₂] [Module R M₃]

/-- Restriction of a transfer map to prescribed signed parts.  The hypothesis
is precisely the sign calculation performed for the Dickson multipliers:
the `A_m` branch preserves sign and the `B_m` branch reverses it. -/
def signedTransfer (Ψ : M₁ × M₂ →ₗ[R] M₃)
    (ι₁ : Module.End R M₁) (ε₁ : R)
    (ι₂ : Module.End R M₂) (ε₂ : R)
    (ι₃ : Module.End R M₃) (ε₃ : R)
    (hsign : ∀ x : signedPart ι₁ ε₁, ∀ y : signedPart ι₂ ε₂,
      Ψ (x.1, y.1) ∈ signedPart ι₃ ε₃) :
    signedPart ι₁ ε₁ × signedPart ι₂ ε₂ →ₗ[R] signedPart ι₃ ε₃ :=
  LinearMap.codRestrict (signedPart ι₃ ε₃)
    (Ψ.comp (LinearMap.prodMap (signedPart ι₁ ε₁).subtype
      (signedPart ι₂ ε₂).subtype))
    (fun z ↦ hsign z.1 z.2)

end SignedPart

section SignedSurjectivity

variable {R M N : Type*} [CommRing R]
  [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]

/-- Averaging onto a signed part, with the inverse of 2 written explicitly. -/
def signProjector (ι : Module.End R M) (ε half : R) : Module.End R M :=
  half • (LinearMap.id + ε • ι)

theorem signProjector_mem (ι : Module.End R M) (ε half : R)
    (hι : ∀ x, ι (ι x) = x) (hε : ε * ε = 1) (x : M) :
    signProjector ι ε half x ∈ signedPart ι ε := by
  rw [mem_signedPart_iff]
  simp only [signProjector, LinearMap.smul_apply, LinearMap.add_apply,
    LinearMap.id_apply, map_smul, map_add, hι, smul_add, smul_smul]
  have he : ε * (half * ε) = half := by rw [mul_left_comm, hε, mul_one]
  rw [he]
  module

theorem signProjector_fix (ι : Module.End R M) (ε half : R)
    (hε : ε * ε = 1) (hhalf : half * 2 = 1)
    (x : signedPart ι ε) : signProjector ι ε half x = x := by
  have hx := mem_signedPart_iff.mp x.property
  simp only [signProjector, LinearMap.smul_apply, LinearMap.add_apply,
    LinearMap.id_apply, hx, smul_smul, hε, one_smul]
  rw [← two_smul R x.val, smul_smul, hhalf, one_smul]

/-- Surjectivity survives restriction to signed parts when 2 is invertible.
For the Dickson transfer, take the source involution `(ι₁,-ι₂)` on the
product. Its ε-part is precisely the ε / -ε pair of source signs. -/
theorem surjective_on_signedPart
    (f : M →ₗ[R] N) (ιM : Module.End R M) (ιN : Module.End R N)
    (ε half : R) (hε : ε * ε = 1) (hhalf : half * 2 = 1)
    (hιM : ∀ x, ιM (ιM x) = x)
    (hequiv : ∀ x, ιN (f x) = f (ιM x))
    (hf : Function.Surjective f) :
    ∀ y : signedPart ιN ε, ∃ x : signedPart ιM ε, f x = y := by
  intro y
  obtain ⟨x, hx⟩ := hf y
  refine ⟨⟨signProjector ιM ε half x, signProjector_mem _ _ _ hιM hε x⟩, ?_⟩
  change f (signProjector ιM ε half x) = y
  have hmap : f (signProjector ιM ε half x) = signProjector ιN ε half (f x) := by
    simp [signProjector, ← hequiv]
  rw [hmap, hx]
  exact signProjector_fix ιN ε half hε hhalf y

end SignedSurjectivity

section SignedProduct

variable {R M₁ M₂ M₃ : Type*} [CommRing R]
  [AddCommGroup M₁] [Module R M₁] [AddCommGroup M₂] [Module R M₂]
  [AddCommGroup M₃] [Module R M₃]

/-- Surjectivity of the actual epsilon / -epsilon restriction of the
two-branch transfer. -/
theorem signedTransfer_surjective
    (Ψ : M₁ × M₂ →ₗ[R] M₃)
    (ι₁ : Module.End R M₁) (ι₂ : Module.End R M₂) (ι₃ : Module.End R M₃)
    (ε half : R) (hε : ε*ε=1) (hhalf : half*2=1)
    (hι₁ : ∀ x, ι₁ (ι₁ x)=x) (hι₂ : ∀ x, ι₂ (ι₂ x)=x)
    (hsign : ∀ x : signedPart ι₁ ε, ∀ y : signedPart ι₂ (-ε),
      Ψ (x.val,y.val) ∈ signedPart ι₃ ε)
    (hequiv : ∀ x y, ι₃ (Ψ (x,y)) = Ψ (ι₁ x,-ι₂ y))
    (hsurj : Function.Surjective Ψ) :
    Function.Surjective (signedTransfer Ψ ι₁ ε ι₂ (-ε) ι₃ ε hsign) := by
  let I : Module.End R (M₁ × M₂) := LinearMap.prodMap ι₁ (-ι₂)
  have hI : ∀ x, I (I x)=x := by
    intro x
    ext <;> simp [I,hι₁,hι₂]
  intro z
  obtain ⟨w,hw⟩ := surjective_on_signedPart Ψ I ι₃ ε half hε hhalf hI
    (fun x => hequiv x.1 x.2) hsurj z
  have hwI := mem_signedPart_iff.mp w.property
  have hx : w.val.1 ∈ signedPart ι₁ ε := by
    rw [mem_signedPart_iff]
    exact congrArg Prod.fst hwI
  have hy : w.val.2 ∈ signedPart ι₂ (-ε) := by
    rw [mem_signedPart_iff]
    have hh := congrArg Prod.snd hwI
    change -ι₂ w.val.2 = ε • w.val.2 at hh
    simpa using congrArg Neg.neg hh
  refine ⟨(⟨w.val.1,hx⟩,⟨w.val.2,hy⟩), ?_⟩
  exact Subtype.ext hw

end SignedProduct

end HeckeCongruences
