"""Small Sage/PARI interface; matrix policy belongs to modular_matrix.py."""
from sage.all import (
    ZZ,
    matrix,
    pari,
)

def pari_howell_row_span(B_mod):
    """
    Compute a Howell basis for the row span of B_mod.

    INPUT:
        B_mod -- matrix over R = Z/nZ whose rows are generators.

    OUTPUT:
        A dictionary containing:
            modulus -- n;
            B_Z     -- an integral lift of B_mod;
            A_Z     -- transpose of B_Z, used by PARI;
            H_pari  -- PARI's Howell basis;
            H_R     -- the Howell basis as a Sage matrix over R.

        The columns of H_R generate the column module generated by A_Z.
        Under transposition, this is the row relation module generated
        by the rows of B_mod.
    """
    R = B_mod.base_ring()
    modulus = ZZ(R.characteristic())
    
    if modulus <= 1:
        raise ValueError("the base ring must have characteristic n > 1")

    B_Z = matrix(
        ZZ,
        B_mod.nrows(),
        B_mod.ncols(),
        [ZZ(x) for x in B_mod.list()]
    )

    # Our generators are rows; PARI expects column generators.
    A_Z = B_Z.transpose()

    H_pari = pari(A_Z).matimagemod(modulus)
    H_R = matrix(R, H_pari.sage())
    # PARI's empty column matrix has no encoded row dimension.
    if H_R.ncols() == 0:
        H_R = matrix(R, B_mod.ncols(), 0)

    if H_R.nrows() != B_mod.ncols():
        raise ArithmeticError(
            "PARI returned a Howell basis with an unexpected "
            "ambient dimension"
        )

    return {
        "modulus": modulus,
        "B_Z": B_Z,
        "A_Z": A_Z,
        "H_pari": H_pari,
        "H_R": H_R,
    }
