"""Canonical strong-signature and theta-orbit bounds from scan files.

This module does not use the legacy ``native_strong_weight_bounds`` manifest.
It identifies a local packet by the labeled finite algebra generated by its
stored Hecke eigenvalues.  A canonical presentation is obtained from the HNF
of the relations among ordered monomials in those eigenvalues.
"""

from __future__ import annotations

from itertools import product
import hashlib
import json
import math
from pathlib import Path

from sage.all import pari


def _canonical_json(value):
    """Serialize a record with sorted keys and fixed separators for reproducible comparison."""
    return json.dumps(value, sort_keys=True, separators=(",", ":"))


def _digest_json(value):
    """Return the SHA-256 identifier of the canonical record; this does not verify its arithmetic."""
    return hashlib.sha256(_canonical_json(value).encode()).hexdigest()


def _weight_character_period(prime, exponent):
    """Exponent of the unit group modulo ``prime^exponent``."""

    if prime != 2:
        return (prime - 1) * prime ** (exponent - 1)
    if exponent == 1:
        return 1
    if exponent == 2:
        return 2
    return 2 ** (exponent - 2)


def _pari_matrix(rows):
    """Convert row data to an exact PARI matrix, including the empty matrix."""
    if not rows:
        return pari.matrix(0, 0, [])
    return pari.matrix(
        len(rows),
        len(rows[0]),
        [entry for row in rows for entry in row],
    )


def _matrix_rows(value):
    """Extract an exact PARI matrix as rows of Python integers."""
    return [
        [int(value[row, column]) for column in range(int(value.ncols()))]
        for row in range(int(value.nrows()))
    ]


def _basis_vector(dimension, position):
    """Return the selected standard basis column in the PARI coordinate convention."""
    return pari.Col(
        [1 if index == position else 0 for index in range(dimension)]
    )


def _det_abs(matrix):
    """Return the absolute determinant of the exact matrix."""
    return abs(int(matrix.matdet()))


def _monomial_vectors(generator_matrices, maximum_degree):
    """Evaluate bounded monomials in the generator matrices on the unit vector.

    Return exponent tuples and coordinate columns in increasing total-degree order.
    """
    dimension = len(generator_matrices[0])
    matrices = [_pari_matrix(rows) for rows in generator_matrices]
    unit = _basis_vector(dimension, 0)
    words = []
    vectors = []
    for exponents in product(
        range(maximum_degree + 1), repeat=len(matrices)
    ):
        if sum(exponents) > maximum_degree:
            continue
        vector = unit
        for matrix, exponent in zip(matrices, exponents):
            for _ in range(exponent):
                vector = matrix * vector
        words.append(tuple(int(value) for value in exponents))
        vectors.append(vector)
    order = sorted(
        range(len(words)), key=lambda index: (sum(words[index]), words[index])
    )
    return [words[index] for index in order], [vectors[index] for index in order]


def local_presentation_fingerprint(
    ideal_lattice,
    generator_matrices,
    maximum_depth=32,
):
    """Return a basis-independent presentation of a labeled finite algebra.

    ``ideal_lattice`` is the column lattice defining the finite quotient, in
    row-matrix notation.  ``generator_matrices`` are multiplication matrices
    for the ordered distinguished Hecke eigenvalues.
    """

    ideal = _pari_matrix(ideal_lattice)
    ideal_order = _det_abs(ideal)
    previous_order = None
    stable_words = None
    stable_vectors = None
    generated_order = None
    progression = []

    for depth in range(maximum_depth + 1):
        words, vectors = _monomial_vectors(generator_matrices, depth)
        evaluations = pari.Mat(vectors)
        span = pari.mathnf(pari.matconcat([ideal, evaluations]))
        span_order = _det_abs(span)
        if ideal_order % span_order:
            raise ArithmeticError("generated subring index is not integral")
        generated_order = ideal_order // span_order
        progression.append(generated_order)
        if generated_order == previous_order:
            stable_words = words
            stable_vectors = vectors
            stable_depth = depth
            break
        previous_order = generated_order
    else:
        raise ArithmeticError("local presentation did not stabilize")

    evaluations = pari.Mat(stable_vectors)
    kernel = pari.matkerint(pari.matconcat([evaluations, -ideal]))
    word_count = len(stable_words)
    projected = pari.matrix(
        word_count,
        int(kernel.ncols()),
        [
            kernel[row, column]
            for row in range(word_count)
            for column in range(int(kernel.ncols()))
        ],
    )
    relations = _matrix_rows(pari.mathnf(projected))
    core = {
        "monomial_order": [list(word) for word in stable_words],
        "stable_total_degree": stable_depth,
        "generated_subring_order": generated_order,
        "order_progression": progression,
        "relation_hnf": relations,
    }
    return {**core, "presentation_sha256": _digest_json(core)}


def twisted_presentation_fingerprint(presentation, generator_scalars, modulus):
    """Return the presentation after scaling each labeled generator."""

    words = [tuple(word) for word in presentation["monomial_order"]]
    word_count = len(words)
    scalars = [
        math.prod(
            pow(int(unit), exponent, modulus)
            for unit, exponent in zip(generator_scalars, word)
        )
        % modulus
        for word in words
    ]
    diagonal = pari.matrix(
        word_count,
        word_count,
        [
            scalars[row] if row == column else 0
            for row in range(word_count)
            for column in range(word_count)
        ],
    )
    relations = _pari_matrix(presentation["relation_hnf"])
    kernel = pari.matkerint(pari.matconcat([diagonal, -relations]))
    projected = pari.matrix(
        word_count,
        int(kernel.ncols()),
        [
            kernel[row, column]
            for row in range(word_count)
            for column in range(int(kernel.ncols()))
        ],
    )
    core = {
        "monomial_order": [list(word) for word in words],
        "stable_total_degree": int(presentation["stable_total_degree"]),
        "generated_subring_order": int(presentation["generated_subring_order"]),
        "order_progression": [
            int(value) for value in presentation["order_progression"]
        ],
        "relation_hnf": _matrix_rows(pari.mathnf(projected)),
    }
    return {**core, "presentation_sha256": _digest_json(core)}


def _multiplication_matrix(nf, element, modulus):
    """Return multiplication by the given element in the p-maximal-order basis modulo the working modulus.

    Reject coordinate denominators that are not units at p.
    """
    dimension = int(pari.poldegree(nf[0]))
    columns = []
    for position in range(dimension):
        basis_element = pari.nfbasistoalg(
            nf, _basis_vector(dimension, position)
        )
        coordinates = pari.nfalgtobasis(nf, element * basis_element)
        column = []
        for entry in coordinates:
            numerator = int(entry.numerator())
            denominator = int(entry.denominator())
            if math.gcd(denominator, modulus) != 1:
                raise ArithmeticError(
                    "Hecke multiplication is not integral in the p-maximal order"
                )
            column.append(
                numerator * pow(denominator, -1, modulus) % modulus
            )
        columns.append(column)
    return [
        [columns[column][row] for column in range(dimension)]
        for row in range(dimension)
    ]


def packet_presentation(packet, prime, exponent, defining_polynomial=None):
    """Construct the canonical labeled-algebra presentation of one packet."""

    modulus = prime**exponent
    rational = packet.get("rational_signature")
    if rational is not None:
        values = [int(value) % modulus for value in rational]
        return local_presentation_fingerprint(
            [[modulus]],
            [[[value]] for value in values],
        )

    polynomial_text = packet.get("local_defining_polynomial")
    if polynomial_text is None:
        polynomial_text = defining_polynomial
    if polynomial_text is None:
        raise ValueError("the packet has no defining polynomial")
    polynomial = pari(polynomial_text)
    nf = pari.nfinit([polynomial, [prime]], 4)
    stored_basis = packet.get("p_maximal_basis")
    if stored_basis is not None:
        reconstructed_basis = [str(value) for value in nf.nf_get_zk()]
        if reconstructed_basis != stored_basis:
            raise ArithmeticError(
                "the reconstructed p-maximal basis does not match the packet"
            )
    coordinate_rows = packet["eigenvalue_residue_basis_coordinates"]
    elements = [
        pari.nfbasistoalg(nf, pari.Col([pari(value) for value in row]))
        for row in coordinate_rows
    ]
    generator_matrices = [
        _multiplication_matrix(nf, element, modulus) for element in elements
    ]

    # PARI serializes a matrix as a sequence of columns.  Convert the stored
    # ideal HNF to the row notation used by ``_pari_matrix``.
    columns = packet["quotient_ideal_hnf_columns"]
    dimension = len(columns)
    ideal_lattice = [
        [int(columns[column][row]) for column in range(dimension)]
        for row in range(dimension)
    ]
    threshold = int(packet["krw_ideal_exponent"])
    residue_degree = int(packet["residue_degree"])
    if _det_abs(_pari_matrix(ideal_lattice)) != prime ** (
        threshold * residue_degree
    ):
        raise ArithmeticError("the stored KRW ideal has the wrong norm")
    return local_presentation_fingerprint(ideal_lattice, generator_matrices)


def canonical_bounds(scan_directory, include_theta=True):
    """Compute strong and theta bounds solely from a completed scan directory."""

    scan_directory = Path(scan_directory)
    summary = json.loads((scan_directory / "summary.json").read_text())
    if not summary["bounded_scan_complete"]:
        raise ValueError("the bounded scan is incomplete")

    prime = int(summary["prime"])
    exponent = int(summary["exponent"])
    modulus = prime**exponent
    period = _weight_character_period(prime, exponent)
    generators = tuple(int(value) for value in summary["hecke_indices"])

    signatures = {}
    theta_orbits = {}
    rational_occurrences = 0
    nonrational_occurrences = 0

    for weight in sorted(int(value) for value in summary["completed_weights"]):
        record = json.loads(
            (scan_directory / f"weight_{weight}.json").read_text()
        )
        if int(record["prime"]) != prime or int(record["exponent"]) != exponent:
            raise ValueError(f"incorrect scan parameters at weight {weight}")
        for orbit in record["orbits"]:
            for packet in orbit["local_packets"]:
                rational = packet.get("rational_signature")
                if rational is None:
                    nonrational_occurrences += 1
                else:
                    rational_occurrences += 1

                # Scalar packets have an immediate canonical presentation.
                # Avoid thousands of unnecessary one-dimensional HNF calls.
                if rational is not None:
                    values = tuple(int(value) % modulus for value in rational)
                    signature_key = _digest_json(
                        {
                            "weight_residue": weight % period,
                            "period": period,
                            "coordinate_primes": list(generators),
                            "rational_eigenvalues": values,
                        }
                    )
                    signatures[signature_key] = min(
                        signatures.get(signature_key, weight), weight
                    )
                    if include_theta:
                        representative = min(
                            (
                                (weight + 2 * theta_power) % period,
                                tuple(
                                    pow(ell, theta_power, modulus) * value
                                    % modulus
                                    for ell, value in zip(generators, values)
                                ),
                            )
                            for theta_power in range(period)
                        )
                        theta_key = _digest_json(
                            {
                                "period": period,
                                "coordinate_primes": list(generators),
                                "rational_representative": representative,
                            }
                        )
                        theta_orbits[theta_key] = min(
                            theta_orbits.get(theta_key, weight), weight
                        )
                    continue

                presentation = packet_presentation(
                    packet,
                    prime,
                    exponent,
                    defining_polynomial=orbit.get("defining_polynomial"),
                )
                signature_core = {
                    "weight_residue": weight % period,
                    "period": period,
                    "coordinate_primes": list(generators),
                    "local_presentation_sha256": presentation[
                        "presentation_sha256"
                    ],
                }
                signature_key = _digest_json(signature_core)
                signatures[signature_key] = min(
                    signatures.get(signature_key, weight), weight
                )

                if include_theta:
                    candidates = []
                    for theta_power in range(period):
                        twisted = twisted_presentation_fingerprint(
                            presentation,
                            [
                                pow(ell, theta_power, modulus)
                                for ell in generators
                            ],
                            modulus,
                        )
                        candidates.append(
                            (
                                (weight + 2 * theta_power) % period,
                                twisted["presentation_sha256"],
                            )
                        )
                    representative = min(candidates)
                    theta_key = _digest_json(
                        {
                            "period": period,
                            "coordinate_primes": list(generators),
                            "representative": {
                                "weight_residue": representative[0],
                                "local_presentation_sha256": representative[1],
                            },
                        }
                    )
                    theta_orbits[theta_key] = min(
                        theta_orbits.get(theta_key, weight), weight
                    )

    report = {
        "prime": prime,
        "exponent": exponent,
        "modulus": modulus,
        "period": period,
        "hecke_indices": generators,
        "largest_completed_weight": max(summary["completed_weights"]),
        "rational_packet_occurrences": rational_occurrences,
        "nonrational_packet_occurrences": nonrational_occurrences,
        "canonical_signature_count": len(signatures),
        "strong_weight_bound": max(signatures.values()),
        "last_weights_with_new_signatures": sorted(set(signatures.values())),
    }
    if include_theta:
        report.update(
            canonical_theta_orbit_count=len(theta_orbits),
            theta_weight_bound=max(theta_orbits.values()),
        )
    return report
