"""Cross-check the finite-chain-ring quotient backend against Smith form."""


# This file was *autogenerated* from the file test_chain_ring_backend.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_7 = Integer(7); _sage_const_42 = Integer(42); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3)
from sage.all import Integers, ZZ, identity_matrix, matrix

from hecke_congruences import (
    chain_ring_manin_quotient_coordinates,
    direct_signed_manin_presentation,
    hecke_matrix_on_signed_manin_quotient,
    manin_quotient_coordinates,
)


def mixed_hom_is_well_defined(A, source_moduli, target_moduli):
    A = matrix(A)
    return (
        A.dimensions() == (len(source_moduli), len(target_moduli))
        and all(
            (ZZ(source_moduli[i]) * ZZ(A[i, j]))
            % ZZ(target_moduli[j]) == _sage_const_0 
            for i in range(A.nrows())
            for j in range(A.ncols())
        )
    )


def mixed_map_is_zero(A, target_moduli):
    A = matrix(A)
    return (
        A.ncols() == len(target_moduli)
        and all(
            ZZ(A[i, j]) % ZZ(target_moduli[j]) == _sage_const_0 
            for i in range(A.nrows())
            for j in range(A.ncols())
        )
    )


def coordinate_change(source, target, coefficient_ring):
    """Matrix from source cyclic coordinates to target coordinates."""
    full_change = source["V_R"].inverse() * target["V_R"]
    return matrix(
        coefficient_ring,
        [
            [
                full_change[i, j]
                for j in target["surviving_indices"]
            ]
            for i in source["surviving_indices"]
        ],
    )


def check_case(p, m, degree, sign, hecke_indices=(_sage_const_2 , _sage_const_7 )):
    R = Integers(p**m)
    presentation = direct_signed_manin_presentation(
        degree,
        R,
        sign,
    )
    chain = chain_ring_manin_quotient_coordinates(presentation)

    # PARI's complete Smith transform has a degenerate 0-column corner
    # case.  The chain-ring backend handles it directly.
    if presentation["ambient_dimension"] == _sage_const_0 :
        assert not chain["surviving_indices"]
        return {
            "degree": degree,
            "sign": sign,
            "coordinate_moduli": tuple(),
            "hecke_indices": tuple(),
        }

    smith = manin_quotient_coordinates(presentation)

    smith_exponents = tuple(smith["surviving_exponents"])
    chain_exponents = tuple(chain["surviving_exponents"])
    assert sorted(smith_exponents) == sorted(chain_exponents), (
        degree,
        sign,
        smith_exponents,
        chain_exponents,
    )

    smith_moduli = tuple(p**e for e in smith_exponents)
    chain_moduli = tuple(p**e for e in chain_exponents)

    if not smith_moduli:
        return {
            "degree": degree,
            "sign": sign,
            "coordinate_moduli": tuple(),
            "hecke_indices": tuple(),
        }

    smith_to_chain = coordinate_change(smith, chain, R)
    chain_to_smith = coordinate_change(chain, smith, R)

    assert mixed_hom_is_well_defined(
        smith_to_chain,
        smith_moduli,
        chain_moduli,
    )
    assert mixed_hom_is_well_defined(
        chain_to_smith,
        chain_moduli,
        smith_moduli,
    )

    assert mixed_map_is_zero(
        smith_to_chain * chain_to_smith
        - identity_matrix(ZZ, len(smith_moduli)),
        smith_moduli,
    )
    assert mixed_map_is_zero(
        chain_to_smith * smith_to_chain
        - identity_matrix(ZZ, len(chain_moduli)),
        chain_moduli,
    )

    checked_hecke_indices = []
    for n in hecke_indices:
        if ZZ(n) % p == _sage_const_0 :
            continue

        smith_hecke = hecke_matrix_on_signed_manin_quotient(
            n,
            presentation,
            smith,
            check_descent=False,
        )["normalized_matrix"]
        chain_hecke = hecke_matrix_on_signed_manin_quotient(
            n,
            presentation,
            chain,
            check_descent=False,
        )["normalized_matrix"]

        assert mixed_map_is_zero(
            smith_hecke * smith_to_chain
            - smith_to_chain * chain_hecke,
            chain_moduli,
        ), (degree, sign, n)
        checked_hecke_indices.append(n)

    return {
        "degree": degree,
        "sign": sign,
        "coordinate_moduli": chain_moduli,
        "hecke_indices": tuple(checked_hecke_indices),
    }


if __name__ == "__main__":
    cases = [
        (degree, sign)
        for degree in range(_sage_const_0 , _sage_const_42 , _sage_const_2 )
        for sign in (_sage_const_1 , -_sage_const_1 )
    ]

    for degree, sign in cases:
        result = check_case(_sage_const_3 , _sage_const_3 , degree, sign)
        print(
            "degree={:2d}, sign={:+d}, moduli={}, T={}".format(
                degree,
                sign,
                result["coordinate_moduli"],
                result["hecke_indices"],
            )
        )

    print("CHAIN-RING BACKEND AGREES WITH SMITH BACKEND")

